config/routes.rb
Rails.application.routes.draw do
  resources :authors do
    resources :books
  end
  resources :orders
  resources :categories
  root :to => 'authors#index'
end

app/models/address.rb
class Address
  include Mongoid::Document
  field :street, type: String
  field :zip, type: Integer
  field :city, type: String
  field :state, type: String
  field :country, type: String
  belongs_to :location, polymorphic: true
end

app/models/author.rb
class Author
  include Mongoid::Document
  field :name, type: String
  validates_presence_of :name
  has_one :address, as: :location, autosave:true, dependent: :destroy
  has_many :books, autosave: true, dependent: :destroy
  accepts_nested_attributes_for :books, :address, allow_destroy: true
end

app/models/book.rb
class Book
  include Mongoid::Document
  field :title, type: String
  field :publisher, type: String
  field :published_on, type: Date
  field :price, localize: true
  field :votes, type: Array
  validates :title, presence: true
  belongs_to :author
  has_and_belongs_to_many :categories
  embeds_many :reviews
end

app/models/category.rb
class Category
  include Mongoid::Document
  field :name, type: String
  has_and_belongs_to_many :books
end

app/models/lease.rb
class Lease
  include Mongoid::Document
  field :from, type: DateTime
  field :till, type: DateTime
  embedded_in :order
end

app/models/order.rb
class Order
  include Mongoid::Document
  field :created_at, type: DateTime
  field :type, type: String #lease, purchase
  belongs_to :book
  belongs_to :member
  embeds_one :lease
  embeds_one :purchase
end

app/models/purchase.rb
class Purchase
  include Mongoid::Document
  field :quantity, type: Integer
  field :price, type: Float
  embedded_in :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  def index
    @authors = Author.all.includes(:books)
  end
  #GET /authors/new
  def new
    @author = Author.new
    @author.build_address
    @author.books.build
  end

  #POST /authors
  def create
    @author = Author.new(params[:author])
    @author.save!
    redirect_to authors_path, notice: "Author created successfully"
  rescue
    render :new
  end

  # GET /authors/:id/edit
  def edit
    @author = Author.find(params[:id])
    @author.build_address unless
    @author.address
    @author.books.build if @author.books.empty?
  end

  #PUT /authors/:id
  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(params[:author])
      redirect_to authors_path, notice: "Author updated successfully"
    else
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => :en}
%head
%meta{:charset => "utf-8"}/
%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
%title Sodibee Library Manager
= javascript_include_tag "application"
= stylesheet_link_tag "application"
= csrf_meta_tags
%body
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    .navbar-header
      = link_to "Sodibee", root_path, :class => 'brand'
      %ul.nav
      .dropdown
        %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
          Authors
          %span.caret
        %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
          %li{:role => "presentation"}
            = link_to "List Authors", authors_path,  html_options: {:role => "menuitem", :tabindex => "-1"}
          %li{:role => "presentation"}
            = link_to "New Author", new_author_path, html_options: {:role => "menuitem", :tabindex => "-1"}
          %li{:role => "presentation"}
            = link_to "Orders", orders_path, html_options: {:role => "menuitem", :tabindex => "-1"}
          %li{:role => "presentation"}
            = link_to "New Order", new_order_path, html_options: {:role => "menuitem", :tabindex => "-1"}
.container
.content
= yield
.footer
%p Library mongo test